### ISSUE TITLE
Gas stats should take inheritance into account

### ISSUE THREAD

**Issue by cag** [gnosis/gnosis-contracts#90]
The gas stats have this going on:

```
Contract: Event
  buyAllOutcomes:
    min: 90982
    max: 135662
    avg: 126726
    med: 135662

...

Contract: CategoricalEvent
  buyAllOutcomes:
    min: 91046
    max: 91046
    avg: 91046
    med: 91046
```
